CREATE ROLE Manager WITH LOGIN PASSWORD 'anhinla';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO Manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO Manager;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO Manager;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO Manager;
GRANT TRIGGER ON ALL TABLES IN SCHEMA public TO Manager;
GRANT CREATE ON SCHEMA public TO Manager;
GRANT USAGE ON SCHEMA public TO Manager;

SELECT * FROM pg_roles WHERE rolname = 'manager';

